masajdProject/masajdApp/urls.py
from django.urls import path
from . import views

app_name = "masajdApp"

urlpatterns = [
    path("home/", views.home_page, name="home"),
    path("add/problem", views.add_problem , name="add_problem "),
    path("view/problem", views.all_problems , name="all_problems"),
    path("problem/detail/<problem_id>/", views.problem_detail, name="problem_detail"),
    path("problem/update/<problem_id>/", views.update_problem , name="update_problem "),
    path("problem/delete/<problem_id>/", views.delete_problem , name="delete_problem "),

]

masajdProject/masajdProject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include ("masajdApp.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

masajdProject/masajdApp/models.py
from django.db import models
from location_field.models.plain import PlainLocationField 

# Create your models here.
class problem (models.Model):
    mosque_name= models.CharField(max_length=512)
    city = models.CharField(max_length=255)
    location = PlainLocationField(based_fields=['city'], zoom=7)
    PhoneNum= models.IntegerField()
    Description =models.TextField()
    image = models.ImageField(upload_to="images/") 

masajdProject/masajdApp/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest, HttpResponse 
from .models import problem 
from django.forms import ModelForm

# Create your views here.

class ProblemForm(ModelForm):

    class Meta:
        model = problem
        fields = "__all__"

def home_page (request : HttpRequest):

     return render(request, "masajdApp/base.html") 



def add_problem (request : HttpRequest):
  
    if request.method == "POST":
        new_problem = problem(mosque_name=request.POST["mosque_name"],city = request.POST["city"] , location=request.POST["location"] , PhoneNum= request.POST["PhoneNum"] , Description=request.POST["Description"], image= request.FILES["image"] )
        new_problem.save()

    return render(request, "masajdApp/add_problem.html", {"problem" : problem, "problemForm": ProblemForm()})



def all_problems (request: HttpRequest):
   problems = problem.objects.all()

   return render(request, "masajdApp/view_problems.html" , {"problems": problems})



def problem_detail(request : HttpRequest, problem_id : int):
  return render(request, "masajdApp/problem_detail.html", {"problem" : problem })
'''
    try:
        problem = problem.objects.get(id= problem_id )
    except:
        return render(request , "masajdApp/not_found.html")
        '''



def update_problem (request: HttpRequest, problem_id:int):

    try:
        post = problem.objects.get(id=problem_id)
    except:
        return render(request , "masajdApp/not_found.html")

    if request.method== "POST":
       problem.mosque_name= request.POST["mosque_name"]
       problem.city = request.POST["city"]
       problem.location=request.POST["location"]
       problem.PhoneNum= request.POST["PhoneNum"]
       problem.Description=request.POST["Description"]
       problem.image= request.FILES["image"] 
       problem.save()

       return redirect("masajdApp:all_problems")

    
    return render(request, "masajdApp/update_problem.html", {"problem" : problem})




def delete_problem (request: HttpRequest, problem_id :int):


    try:
        post = problem.objects.get(id= problem_id)
    except:
        return render(request , "masajdApp/not_found.html")
        
    problem.delete() 

    return redirect("masajdApp:all_problems")

masajdProject/masajdApp/templates/masajdApp/add_problem.html
{% extends 'masajdApp/base.html' %}


{% block title %} Add New problem {% endblock %}


{% block content %}
  <h1>Add New Post</h1>

  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label  class="form-label">mosque_name</label>
        <input type="text" class="form-control" name="mosque_name">
    </div>

    <div class="mb-3">
        <label  class="form-label">Description</label>
        <textarea type="text" class="form-control" name="Description "></textarea>
    </div>

    <div class="mb-3">
        <label  class="form-label">city</label>
        <input type="text" class="form-control" name="city">
    </div>
    <div class="mb-3">
        <label  class="form-label">location</label>
        <input type="text" class="form-control" name="location">
        
    </div>
    <div class="mb-3">
        <label  class="form-label"> PhoneNum</label>
        <input type="text" class="form-control" name="PhoneNum">
    </div>

    
    
    <div class="mb-3"> 
    <label  class="form-label"> Image</label>
        <input type="file" name="image" accept="image/*" class="form-control" />
     </div>

     <div class="mb-3"> 
        <input class="btn btn-primary" type="submit" value="submit" />
    </div>
        

    </form>

{{ProblemForm}}

{% endblock %}

masajdProject/masajdApp/templates/masajdApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Agency - Start Bootstrap Theme</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles/styles.css' %}">
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico'%}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'styles/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div class="container-fluid">
            <nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
                <div class="container-fluid">
                  <a class="navbar-brand" href="#">MASAJD </a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
            
                  <div class="collapse navbar-collapse" id="navbarsExample02">
                    <ul class="navbar-nav me-auto">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'masajdApp:all_problems' %}"> PROBLEMS</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'masajdApp:add_problem ' %}">Add PROBLEM </a>
                      </li>
                    </ul>
                    <form role="search">
                      <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                    </form>
                  </div>
                </div>
              </nav>
    
              <div class="container  pt-4">
                {% block content  %}
                {% endblock %}
              </div>
        </div>
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
      </body>
    </html>
    

masajdProject/masajdApp/templates/masajdApp/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>{% block title %} Masajd project {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">>
  </head>
  <body>
    {% block content  %}
      <h1>Hello, world!</h1>
     {% endblock %}
   
  </body> 

masajdProject/masajdApp/templates/masajdApp/not_found.html
{% extends "masajdApp/base.html" %}

{% block title %} Not found {% endblock %}

{% block content  %}
<h1>Not Found!</h1>
{% endblock %}

masajdProject/masajdApp/templates/masajdApp/problem_detail.html
{% extends "masajdApp/base.html" %}

{% block title %} {{ problem.mosque_name }} {% endblock %}


{% block content %}
<h1>{{ problem.mosque_name }}</h1>
<div class="container">
    <p>{{problem.city}}</p>
    <p>{{problem.location}}</p>
    <p>{{problem.PhoneNum}}</p>
    
    <img src="{{problem.images.url }}"  class="w-100"/>
    <div>
        {{problem.Description}}
    </div>
</div>

{% endblock %}

   

masajdProject/masajdApp/templates/masajdApp/update_problem.html
{% extends 'masajdApp/base.html' %}

{% block title %} Update  {% endblock %}

{% block content %}
    <h1>Update {{  problem.mosque_name }}</h1>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label  class="form-label">mosque_name</label>
            <input type="text" class="form-control" name="mosque_name" value="{{ problem.mosque_name }}">
        </div>

        <div class="mb-3">
            <label  class="form-label">Description</label>
            <textarea type="text" class="form-control" name="Description">{{ problem.Description }}</textarea>
        </div>

        <div class="mb-3">
            <label  class="form-label">City </label>
            <input type="text" class="form-control" name="city" value="{{ problem.city }}" />
        </div>

        <div class="mb-3">
            <label  class="form-label">location</label>
            <input type="text" class="form-control" name="location" value="{{ problem.location }}">
        </div>

        <div class="mb-3">
                <label  class="form-label"> PhoneNum</label>
                <input type="text" class="form-control" name="PhoneNum" value="{{ problem.PhoneNum}}">
        </div>   

        <div class="mb-3"> 
            <label  class="form-label">Post Image</label>
                <input type="file" name="image" accept="image/*" class="form-control" value="{{ problem.image}}" />
             </div>        
        
        <input class="btn btn-primary" type="submit" value="Update " />
    </form>
{% endblock %}

masajdProject/masajdApp/templates/masajdApp/view_problems.html
{% extends 'masajdApp/base.html' %}

{% block title %} all problem {% endblock %}




{% block content %}

<h1> problem </h1>
<div class="container">
    <table class="table">
        <thead>
        <tr> 
            <th scope="col">mosque_name </th>
            <th scope="col">city</th>
            <th scope="col">Location</th>
            <th scope="col">Description</th>
            <th scope="col">Edit</th>
            
        </tr>
        </thead>
        <tbody>
            {%for problem in problems%}
            <tr>
                <th scope="row"><a href="{% url 'masajdApp:problem_detail' problem.id %}">{{problem.mosque_name}}</a></th>
                <td>{{ problem.city}}</td>
                <td>{{ problem.location}}</td>
                <td>{{ problem.Description}}</td>
                
                <td>

                    <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Edit
                        </button>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'masajdApp:update_problem ' problem.id %}">Update</a></li>
                          <li><a class="dropdown-item" href="{% url 'masajdApp:delete_problem ' problem.id %}">Delete</a></li>
                        </ul>
                      </div>

                </td>
            </tr>
             {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}